# Generated by Django 5.2 on 2025-04-18 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер')),
                ('room_type', models.CharField(choices=[('comfort', 'Комфорт'), ('comfort_plus', 'Комфорт+'), ('apartment', 'Апартаменты')], max_length=50, verbose_name='Тип номера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за ночь')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RoomBookedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Занятая дата')),
            ],
            options={
                'verbose_name': 'Занятая дата номера',
                'verbose_name_plural': 'Занятые даты номеров',
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mainapp.room'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('room', 'check_in', 'check_out'), name='unique_room_booking'),
        ),
        migrations.AddField(
            model_name='roombookeddate',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='mainapp.booking', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='roombookeddate',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_dates', to='mainapp.room'),
        ),
        migrations.AlterUniqueTogether(
            name='roombookeddate',
            unique_together={('room', 'date')},
        ),
    ]
