# Generated by Django 5.2 on 2025-04-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_restaurant_cart_dish_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, choices=[('comfort', 'img/room2.jpg'), ('comfort_plus', 'img/room3.jpg'), ('apartment', 'img/room7.jpg')], upload_to='', verbose_name='Изображение номера'),
        ),
    ]
