# Generated by Django 5.2 on 2025-04-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
