# Generated by Django 5.2 on 2025-04-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='type',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(choices=[('restaurant1', 'Ресторан: Вкусный Дом'), ('restaurant2', 'Ресторан: Гурме Хаус'), ('bar', 'Бар: Sky Lounge Bar')], max_length=100, verbose_name='Название'),
        ),
    ]
