# Generated by Django 5.2 on 2025-04-27 02:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='static/dishes/', location='C:\\Users\\Elisa\\OneDrive\\Рабочий стол\\Работа\\Elist-Regency\\static\\dishes'), upload_to='', verbose_name='Фото блюда'),
        ),
    ]
