# Generated by Django 5.2 on 2025-04-27 08:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='static/rooms/', location='C:\\Users\\Elisa\\OneDrive\\Рабочий стол\\Работа\\Elist-Regency\\static\\rooms'), upload_to='', verbose_name='Фото номера'),
        ),
    ]
