# Generated by Django 5.2 on 2025-04-27 12:36

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_dish_image_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/dishes/', location='C:\\Users\\Elisa\\OneDrive\\Рабочий стол\\Работа\\Elist-Regency\\static/img\\dishes'), upload_to='', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/rooms/', location=pathlib.PureWindowsPath('C:/Users/Elisa/OneDrive/Рабочий стол/Работа/Elist-Regency/static/img/rooms')), upload_to='', verbose_name='Фото номера'),
        ),
    ]
