# Generated by Django 5.0.6 on 2025-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_cartitem_unique_together_cart_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'звезда'), (2, 'звезды'), (3, 'звезды'), (4, 'звезды'), (5, 'звезд')], verbose_name='Оценка'),
        ),
    ]
