# Generated by Django 5.0.6 on 2025-05-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_review_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата клининга')),
                ('order_time', models.TimeField(verbose_name='Время клининга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_orders', to='mainapp.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Заказ клининга',
                'verbose_name_plural': 'Заказы клининга',
                'ordering': ['-created_at'],
            },
        ),
    ]
